# Create a Deployment file for eureka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
spec:
  replicas: {{ .Values.replicas.default }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
  #    imagePullSecrets:
  #    - name:  jfrog-docker-secret
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.name}}:{{ .Values.image.tag }}"

        