---
apiVersion: v1
kind: Service
metadata:
  name: i27-eureka-dev-svc
spec:
  selector:
    app: i27-eureka-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: NodePort   #ClusterIP

  